apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet
        image: kayketeixeira/dotnet-app:v0.0.1
        ports:
        - containerPort: 80
        env: 
          - name: DD_TAGS
            value: "cost-center:1234567890"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: dotnet-app
  ports:
  - name: http
    port: 8081
    targetPort: 80