apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: default
  labels:
    tags.datadoghq.com/env: "local" # Unified service tag - Deployment Env tag
    tags.datadoghq.com/service: "java-app" # Unified service tag - Deployment Service tag
    tags.datadoghq.com/version: "1.0" # Unified service tag - Deployment Version tag
spec:
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.33.0"
        ad.datadoghq.com/java.logs: '[{"source":"java","service":"java-app"}]'
      labels:
        tags.datadoghq.com/env: "local" # Unified service tag - Pod Env tag
        tags.datadoghq.com/service: "java-app" # Unified service tag - Pod Service tag
        tags.datadoghq.com/version: "1.1" # Unified service tag - Pod Version tag
        admission.datadoghq.com/enabled: "true" # Enable Admission Controller to mutate new pods part of this deployment
        app: java-app
    spec:
      containers:
      - name: java
        image: kayketeixeira/java-app:v0.0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
  - name: http
    port: 8083
    targetPort: 80