apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelgen-deployment
  labels:
    app: otelgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelgen
  template:
    metadata:
      labels:
        app: otelgen
    spec:
      containers:
      - name: otelgen
        image: ghcr.io/krzko/otelgen:latest
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 256Mi
            cpu: 100m  
        args: 
          - "--insecure"
          - "--otel-exporter-otlp-endpoint"
          - "<endpoint-here>:4317"    
          - "--protocol"
          - "grpc"
          - "metrics"
          - "exponential-histogram"